name: Deploy 4.github_pages_deployment to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'Projects/4.github_pages_deployment/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get the code from your repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Deploy just your chosen folder to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./Projects/4.github_pages_deployment
          github_token: ${{ secrets.GITHUB_TOKEN }}
