name: CI - Lint and Test

on:
  push:
    branches: [main]
    paths:
      - 'Projects/4.1.linting_and_testing/**'
      - '.github/workflows/ci.yml'
      - 'requirements.txt'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          # Lint only the target folder
          flake8 Projects/4.1.linting_and_testing

      - name: Run tests with pytest
        working-directory: Projects/4.1.linting_and_testing
        run: pytest
