name: Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - main
    paths:
      - 'Projects/4.0.github_pages_deployment/**'

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./Projects/4.0.github_pages_deployment
          server-dir: /htdocs/
